apiVersion: v1
kind: Namespace
metadata:
  name: animal-app
---
# MongoDB Service & Deployment
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: animal-app
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: animal-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:6.0
        ports:
        - containerPort: 27017
---
# Login Service
apiVersion: v1
kind: Service
metadata:
  name: login-service
  namespace: animal-app
spec:
  type: NodePort
  selector:
    app: login-service
  ports:
    - port: 5005
      targetPort: 5005
      nodePort: 30005
      
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-service
  namespace: animal-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login-service
  template:
    metadata:
      labels:
        app: login-service
    spec:
      containers:
      - name: login-service
        image: animals-watchlist/user-service:local
        imagePullPolicy: IfNotPresent
        env:
        - name: MONGO_URI
          value: mongodb://mongodb-service:27017/
        - name: PET_SERVICE_URL
          value: http://pet-service:5006
        ports:
        - containerPort: 5005
---
# Pet Service
apiVersion: v1
kind: Service
metadata:
  name: pet-service
  namespace: animal-app
spec:
  type: NodePort
  selector:
    app: pet-service
  ports:
    - port: 5006
      targetPort: 5006
      nodePort: 30006
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pet-service
  namespace: animal-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pet-service
  template:
    metadata:
      labels:
        app: pet-service
    spec:
      containers:
      - name: pet-service
        image: animals-watchlist/pet-service:local
        imagePullPolicy: IfNotPresent
        env:
        - name: MONGO_URI
          value: mongodb://mongodb-service:27017/
        ports:
        - containerPort: 5006
